//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public maintenance_master()
        {
            this.maintenance_schedule = new HashSet<maintenance_schedule>();
        }
    
        public string MaintenanceMasterId { get; set; }
        public string EquipmentPartId { get; set; }
        public string Description { get; set; }
        public string Periodicity { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTs { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedTs { get; set; }
        public Nullable<bool> EmergencyMaintenance { get; set; }
        public long tranx_id { get; set; }
    
        public virtual equipment_master equipment_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maintenance_schedule> maintenance_schedule { get; set; }
    }
}
