//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance_schedule
    {
        public string MaintenanceMasterId { get; set; }
        public string MaintenanceScheduleId { get; set; }
        public Nullable<System.DateTime> InitialEstimatedDateOfStart { get; set; }
        public Nullable<System.DateTime> RevisedEstimatedDateOfStart { get; set; }
        public Nullable<System.DateTime> InitialEstimatedDateOfCompletion { get; set; }
        public Nullable<System.DateTime> RevisedEstimatedDateOfCompletion { get; set; }
        public string Technician { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTs { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedTs { get; set; }
    
        public virtual maintenance_master maintenance_master { get; set; }
    }
}
