//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPMEntities : DbContext
    {
        public PPMEntities()
            : base("name=PPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Defect> Defect { get; set; }
        public virtual DbSet<Diary> Diary { get; set; }
        public virtual DbSet<EquipmentMaster> EquipmentMaster { get; set; }
        public virtual DbSet<FinancialCases> FinancialCases { get; set; }
        public virtual DbSet<PlannedMaintenance> PlannedMaintenance { get; set; }
        public virtual DbSet<PlannedMaintenanceSchedule> PlannedMaintenanceSchedule { get; set; }
        public virtual DbSet<Ship> Ship { get; set; }
        public virtual DbSet<Task> Task { get; set; }
    }
}
