//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Owner { get; set; }
        public string DefectId { get; set; }
        public string PpmsId { get; set; }
        public string EquipmentPartId { get; set; }
        public string FinCaseId { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> InitialEstimatedDateS { get; set; }
        public Nullable<System.DateTime> RevisedEstimatedDateS { get; set; }
        public Nullable<System.DateTime> InitialEstimatedDateC { get; set; }
        public Nullable<System.DateTime> RevisedEstimatedDateC { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTs { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedTs { get; set; }
    }
}
